apiVersion: platform.flowcd.io/v1alpha1
kind: Pipeline
metadata:
  labels:
    app.kubernetes.io/name: flowcd
    app.kubernetes.io/managed-by: flowcd-operator
  name: pipeline-sample
spec:
  appRef: app-sample
  registry: ghcr.io/myorg
  imageName: my-app
  dockerfilePath: Dockerfile
  buildArgs:
    - name: NODE_ENV
      value: production
