apiVersion: platform.flowcd.io/v1alpha1
kind: MyResource
metadata:
  labels:
    app.kubernetes.io/name: operator-new
    app.kubernetes.io/managed-by: kustomize
  name: myresource-sample
spec:
  # TODO(user): Add fields here
